### ISSUE TITLE
比较严重的问题

### ISSUE THREAD

**Issue by Steve-337** [Oliviaophia/SmartTaskbar#106]
开启软件后有极大的概率导致资源管理器假死（任务栏无法唤起，键盘按win键无法打开开始界面），只能快捷键打开任务管理器重启资源管理器。
貌似是在弹出通知后会假死（因为每次重启资源管理器后都会弹出来其他应用的通知）

**Comment by ChanpleCai** [comment]
这个我自己还没有遇到，目前软件还没有对任务栏做什么侵入性的hook之类的，应该不至于吧。

**Comment by ChanpleCai** [comment]
你用的是dev之类的win11么

**Comment by Steve-cn** [comment]
> 你用的是dev之类的win11么

用的是beta的win11

**Comment by Steve-cn** [comment]
> 这个我自己还没有遇到，目前软件还没有对任务栏做什么侵入性的hook之类的，应该不至于吧。

好像就是目前的最新版更新后出现的问题，之前没有遇到过，我再打开软件试试会不会再次出现这个问题

**Comment by Steve-cn** [comment]
刚刚试了一下，果然又假死了，还是只能重启资源管理器，暂时不清楚百分百复现的方法
