### ISSUE TITLE
win11打开搜索时状态栏会不停隐藏和显示

### ISSUE THREAD

**Issue by Steve-337** [Oliviaophia/SmartTaskbar#95]
点击开始里面的搜索框后状态栏就会抽风，已经是最新版

**Comment by ChanpleCai** [comment]
有百分比复现的方法么？我看看能不能复现你的bug

**Comment by Steve-cn** [comment]
> 有百分比复现的方法么？我看看能不能复现你的bug

已经发现问题所在了，和startallback的增强型经典任务栏功能冲突，禁用此功能就正常了

**Comment by ChanpleCai** [comment]
我装个startisback看看它什么原理，如果可以绕开的话，就处理一下，比较复杂的话，可能就放着不管了。

**Comment by ChanpleCai** [comment]
试了下一切正常啊，你确认装的是最新版本的startallback么？

**Comment by ChanpleCai** [comment]
我搞明白了，它这个搜索框，在自动隐藏模式下，打开的时候窗体会固定在任务栏的一半的位置。这时候跟SmartTaskbar判断就是相交的，然后任务栏就隐藏了；然后它在任务栏完全隐藏的时候，又会自动上移动搜索框，这时候就满足不相交情况，SmartTaskbar控制任务栏显示了，然后搜索框又被移动到任务栏的1/2位置。无限循环

**Comment by ChanpleCai** [comment]
新版本已经修复了，你试试

**Comment by Steve-cn** [comment]
> 新版本已经修复了，你试试

感谢，此问题的确得到了修复。
但更新win11后一直有个问题，就是有时处于桌面状态时任务栏仍然是隐藏，重新开关智能模式后恢复正常。
